image: cyclenerd/scp-tools-gitlab:latest

stages:
  - init
  - validation
  - build
  - test
  - deploy
 
before_script:
  - echo "$CI_BUILD_REPO"
  - echo "$CI_BUILD_NAME"
  - echo "$CI_PIPELINE_ID"
  - echo "$CI_PIPELINE_IID"
  - echo "$CI_COMMIT_REF_SLUG"
  - echo "$CI_PROJECT_PATH"
  - echo "$CI_PROJECT_DIR"
  - java -version
  - whoami
  - pwd
  - node -v
  - npm -v

init-ci:
  stage: init
  script:
    - npm update -g
    - npm install
    - node_modules/grunt-cli/bin/grunt --verbose clean
  artifacts:
    paths:
    - node_modules/

code-validation: 
   stage: validation 
   script:
     - node_modules/grunt-cli/bin/grunt -d -v fiori-test
   dependencies:
    - init-ci

build-app: 
   stage: build 
   script: 
    - date=`date +%Y%m%d%H%M%S`
    - echo $date
    - sed -ie "s/\${timestamp}/$date/g" mta.yaml
    - mkdir -p build/
    - echo "$date" > build/variables
    - java -jar $MTA_BUILDER_HOME/mta_archive_builder.jar --mtar build/tmp-$date.mtar --build-target=NEO build
   artifacts:
    paths:
    - build/

unit-test: 
   stage: test 
   script: 
     - node_modules/grunt-cli/bin/grunt -d -v unit-test
   dependencies:
    - init-ci

deploy-scp: 
    stage: deploy 
    script:
    - date=`cat build/variables`
    - echo $date
    - echo $SCP_HOST
    - neo.sh deploy-mta --user "$SCP_USER" --host "$SCP_HOST" --source build/tmp-$date.mtar --account "$SCP_ACCOUNT" --password "$SCP_PWD" --synchronous
    dependencies:
    - build-app
    only:
    - master
