image: cyclenerd/scp-tools-gitlab:latest

stages:
  - init
  - validation
  - build
  - deploy
 
before_script:
  - echo "$CI_BUILD_REPO"
  - echo "$CI_BUILD_NAME"
  - echo "$CI_PIPELINE_ID"
  - echo "$CI_PIPELINE_IID"
  - echo "$CI_COMMIT_REF_SLUG"
  - echo "$CI_PROJECT_PATH"
  - echo "$CI_PROJECT_DIR"
  - java -version
  - whoami
  - pwd
  - node -v
  - npm -v

init-ci:
  stage: init
  script:
    - npm update
    - npm install
    - node_modules/grunt-cli/bin/grunt --verbose clean
  artifacts:
    paths:
    - node_modules/

code-validation: 
   stage: validation 
   script:
     - node_modules/grunt-cli/bin/grunt -d -v fiori-test
   dependencies:
    - init-ci

build-app: 
   stage: build 
   script: 
    - date=`date +%Y%m%d%H%M%S`
    - echo $date
    - sed -ie "s/\${timestamp}/$date/g" mta.yaml
    - mkdir -p build/
    - echo "$date" > build/variables
    - java -jar $MTA_BUILDER_HOME/mta_archive_builder.jar --mtar build/tmp-$date.mtar --build-target=NEO build
   artifacts:
    paths:
    - build/

autogen-doc:
    stage: deploy
    script:
    - npm install
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.informatik.hu-berlin.de/sp_fs_2019_mob/mobilitaetskonto.wiki.git
    - rm -rf mobilitaetskonto.wiki/doc/*
    - node gen-doc.js mobilitaetskonto.wiki/ webapp/
    - cd mobilitaetskonto.wiki
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git add -A
    - git diff --quiet && git diff --staged --quiet || git commit -m "update jsDoc ${GITLAB_USER_LOGIN} ${GITLAB_USER_NAME} ${CI_COMMIT_SHORT_SHA}"
    - git push "https://${GITLAB_USER}:${CI_GIT_TOKEN}@gitlab.informatik.hu-berlin.de/sp_fs_2019_mob/mobilitaetskonto.wiki.git" HEAD:master
    dependencies:
    - build-app
    only:
    - master

deploy-scp: 
    stage: deploy 
    script:
    - date=`cat build/variables`
    - echo $date
    - echo $SCP_HOST
    - neo.sh deploy-mta --user "$SCP_USER" --host "$SCP_HOST" --source build/tmp-$date.mtar --account "$SCP_ACCOUNT" --password "$SCP_PWD" --synchronous
    dependencies:
    - build-app
    only:
    - master
